### ISSUE TITLE
2024 TODO

### ISSUE THREAD

**Issue by qaqland** [qaqland/apk-search#3]
- [ ] Dark Mode
- [ ] Mobile: p-2
- [ ] Select.jsx more css
- [ ] GitHub link
- [ ] Offical link
- [ ] provide/require sort
- [ ] more search weight on provide 
- [ ] ? ads ?
- [ ] update status
- [ ] pagination auto to top
- [ ] fix loading
- [ ] first page without search or time sorted
- [ ] add title and logo
- [ ] add LICENSE
- [ ] cursor changes when hover

**Comment by qaqland** [comment]
Add Status Badges

![](https://healthchecks.io/badge/87bca750-2e95-4d99-b13b-a832b8/rOCvR9MR.svg)

**Comment by qaqland** [comment]
- [ ] change string to number that could compare

https://github.com/qaqland/apk-search/blob/3d374f52b6064ba613edb5d16dfec02651256acc/main.go#L50
